/**
 * Generates a stable, unique ID for a DOM element.
 * Priority:
 * 1. Stable ID attribute (ignoring auto-generated looking IDs)
 * 2. Data attributes (data-testid, data-cy, etc.)
 * 3. Fallback to a generated ID based on tag, path, and index/counter
 */
export function generateNodeId(
  element: Element,
  fallbackIndex?: number
): string {
  // 1. Check for stable ID
  if (element.id) {
    // Filter out obviously auto-generated IDs
    if (!isAutoGeneratedId(element.id)) {
      return element.id;
    }
  }

  // 2. Check for testing/stable data attributes
  const stableAttributes = [
    "data-testid",
    "data-test-id",
    "data-cy",
    "data-qa",
    "data-automation-id",
    "data-component",
    "data-key",
  ];

  for (const attr of stableAttributes) {
    if (element.hasAttribute(attr)) {
      return `${element.tagName.toLowerCase()}-${element.getAttribute(attr)}`;
    }
  }

  // 3. Fallback
  // If a fallback index is provided, use it (e.g. from traversal counter)
  if (fallbackIndex !== undefined) {
    return `node-${fallbackIndex}`;
  }

  // Otherwise generate a hash-like ID (less stable but unique)
  return `gen-${element.tagName.toLowerCase()}-${Math.random()
    .toString(36)
    .substr(2, 9)}`;
}

function isAutoGeneratedId(id: string): boolean {
  // Common patterns for auto-generated IDs
  const autoPatterns = [
    /^ember\d+/,
    /^react-/,
    /^vue-/,
    /^ng-/,
    /-\d{5,}$/, // Ends with long number
    /^[a-z0-9]{8}-[a-z0-9]{4}-/, // UUID-like
    /^__/,
    /:\d+$/, // Scoped styles often append :123
  ];

  return autoPatterns.some((pattern) => pattern.test(id));
}
